### ISSUE TITLE
I get an error when running the app

### ISSUE THREAD

**Issue by jellyNoone** [lab-box/adyen_flutter#1]
C:\..\flutter\.pub-cache\hosted\pub.dartlang.org\adyen_flutter-0.0.3\android\src\main\java\com\pikaway\adyen_flutter\AdyenFlutterPlugin.java:16: error: cannot find symbol
import com.adyen.checkout.base.HostProvider;
                              ^
  symbol:   class HostProvider
  location: package com.adyen.checkout.base
C:\..\flutter\.pub-cache\hosted\pub.dartlang.org\adyen_flutter-0.0.3\android\src\main\java\com\pikaway\adyen_flutter\AdyenFlutterPlugin.java:144: error: cannot find symbol
    private String fetchPublicKey(HostProvider hostProvider, String publicKeyToken) throws Error {
                                  ^
  symbol:   class HostProvider
  location: class AdyenFlutterPlugin
C:\...\flutter\.pub-cache\hosted\pub.dartlang.org\adyen_flutter-0.0.3\android\src\main\java\com\pikaway\adyen_flutter\AdyenFlutterPlugin.java:76: error: cannot find symbol
        HostProvider hostProvider = environment.equals("TEST") ? CardApi.TEST : CardApi.LIVE_EU;
        ^
  symbol:   class HostProvider
  location: class AdyenFlutterPlugin
C:\...\flutter\.pub-cache\hosted\pub.dartlang.org\adyen_flutter-0.0.3\android\src\main\java\com\pikaway\adyen_flutter\AdyenFlutterPlugin.java:110: error: cannot find symbol
        HostProvider hostProvider = environment.equals("TEST") ? CardApi.TEST : CardApi.LIVE_EU;
        ^
  symbol:   class HostProvider
  location: class AdyenFlutterPlugin
C:\...\flutter\.pub-cache\hosted\pub.dartlang.org\adyen_flutter-0.0.3\android\src\main\java\com\pikaway\adyen_flutter\AdyenFlutterPlugin.java:146: error: cannot access Api
        CardApi cardApi = CardApi.getInstance(this.activity.getApplication(), hostProvider);
                                 ^
  class file for com.adyen.checkout.base.internal.Api not found
Note: C:\...\flutter\.pub-cache\hosted\pub.dartlang.org\adyen_flutter-0.0.3\android\src\main\java\com\pikaway\adyen_flutter\AdyenFlutterPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by jellyNoone** [comment]
I was able to get my app running if I disabled the plugin, build it and then get the plugin back and run packages get. However when providing all the information in the example I was greated with this error.


E/flutter ( 1608): #3      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:566
E/flutter ( 1608): #4      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:166
E/flutter ( 1608): #5      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:240
E/flutter ( 1608): #6      TapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:211
E/flutter ( 1608): #7      GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
E/flutter ( 1608): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:225
E/flutter ( 1608): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:199
E/flutter ( 1608): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter ( 1608): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter ( 1608): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter ( 1608): #13     _rootRunUnary  (dart:async/zone.dart:1136:13)
E/flutter ( 1608): #14     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter ( 1608): #15     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
E/flutter ( 1608): #16     _invoke1  (dart:ui/hooks.dart:233:10)
E/flutter ( 1608): #17     _dispatchPointerDataPacket  (dart:ui/hooks.dart:154:5)
E/flutter ( 1608):

**Comment by jellyNoone** [comment]
E/flutter ( 1608): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Exception: Could not encrypt the token from the card:MissingPluginException(No implementation found for method encryptedToken on channel adyen_flutter)
E/flutter ( 1608): #0      AdyenFlutter.encryptedToken  (package:adyen_flutter/adyen_flutter.dart:35:7)
E/flutter ( 1608): <asynchronous suspension>
E/flutter ( 1608): #1      _StatePaymentPage.build.<anonymous closure> 
package:workable_app_frame/…/ProjectPage/PaymentPage.dart:254
E/flutter ( 1608): <asynchronous suspension>
E/flutter ( 1608): #2      _InkResponseState._handleTap 
E/flutter ( 1608): #3      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:566
E/flutter ( 1608): #4      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:166
E/flutter ( 1608): #5      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:240
E/flutter ( 1608): #6      TapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:211
E/flutter ( 1608): #7      GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
E/flutter ( 1608): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:225
E/flutter ( 1608): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:199
E/flutter ( 1608): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter ( 1608): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter ( 1608): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter ( 1608): #13     _rootRunUnary  (dart:async/zone.dart:1136:13)
E/flutter ( 1608): #14     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter ( 1608): #15     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
E/flutter ( 1608): #16     _invoke1  (dart:ui/hooks.dart:233:10)
E/flutter ( 1608): #17     _dispatchPointerDataPacket  (dart:ui/hooks.dart:154:5)
E/flutter ( 1608):

**Comment by AlexandreRoba** [comment]
Hello, Is this a new project or an existing one?

**Comment by AlexandreRoba** [comment]
Can you tell me if your Android project has been migrated on AndroidX?

**Comment by jellyNoone** [comment]
I started this project back in March this year. I'm new to mobile development so could you please guide me on how to check this.

**Comment by AlexandreRoba** [comment]
i install the component on a fresh app and I have no error.@jellyNoone Do you mind posting your pubspec.yaml dependencies? thanks.

**Comment by loveuqian** [comment]
@AlexandreRoba 
i install the component on a fresh **iOS** app and I have an error.
can u give a help, thanks.
![image](https://user-images.githubusercontent.com/9745332/61451971-4daa4c80-a98d-11e9-9223-3c754bda0fc0.png)
![image](https://user-images.githubusercontent.com/9745332/61451980-53a02d80-a98d-11e9-883b-8c2049e7e392.png)
